name: careconnect
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_app_name: ^0.1.0
  flutter_lints: ^5.0.0

flutter_app_name:
  name: "Care Connect"



flutter:
  uses-material-design: true

  assets:
    - assets/images/icon.png
    - assets/images/
