name: careconnect
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.18.0
  cupertino_icons: ^1.0.8
  youtube_player_iframe: ^4.0.4
  provider: ^6.1.2
  http: ^0.13.6
  shared_preferences: ^2.2.0  
  image_picker: ^1.1.2
  google_sign_in: ^6.1.6
  sign_in_with_apple: ^5.0.0
  firebase_auth: ^4.15.3
  flutter_local_notifications: ^18.0.1
  firebase_messaging: ^14.7.10
  firebase_core: ^2.32.0
  cloud_firestore: ^4.17.5
  # firebase_messaging: ^14.6.7
  # firebase_core: ^3.13.0
  # cloud_firestore: ^5.6.6
 
  # Update to a more stable version

  

dev_dependencies:
  flutter_test:
    sdk: flutter
  # flutter_app_name: ^0.1.0
  flutter_lints: ^5.0.0
  url_launcher: ^6.3.1

flutter_app_name:
  name: "Care Connect"

flutter:
  uses-material-design: true

  assets:
    - assets/images/icon.png
    - assets/images/
